-- 00_bootstrap.sql — account-level containers. Run as ACCOUNTADMIN. Idempotent.
USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS FIU_WH
    WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
    COMMENT = 'FIU-IND AML Copilot compute (XS; Cortex Search refresh + app queries)';
CREATE DATABASE IF NOT EXISTS FIU_COPILOT COMMENT = 'FIU-IND AML Decision-Defensibility Copilot (SYNTHETIC DATA ONLY)';
CREATE SCHEMA   IF NOT EXISTS FIU_COPILOT.AML;
