-- 03_grants.sql — app-role privileges. Run as ACCOUNTADMIN AFTER the objects exist
-- (domain/corpus/export/ddl/*.sql + scripts/setup_alerts.py). Idempotent.
--
-- THE ENFORCEMENT: FIU_APP_ROLE gets SELECT + INSERT on DECISION_LEDGER and NOTHING ELSE on it.
-- UPDATE / DELETE / TRUNCATE are not granted; the REVOKE lines make that explicit and also clean up
-- any earlier over-grant. deploy/04_verify_ledger_rbac.sql then PROVES the denial.
USE ROLE ACCOUNTADMIN;
USE DATABASE FIU_COPILOT;
USE SCHEMA AML;

GRANT USAGE ON WAREHOUSE FIU_WH      TO ROLE FIU_APP_ROLE;
GRANT USAGE ON DATABASE  FIU_COPILOT TO ROLE FIU_APP_ROLE;
GRANT USAGE ON SCHEMA    FIU_COPILOT.AML TO ROLE FIU_APP_ROLE;

-- Read-only reference / case data (the app never writes these).
GRANT SELECT ON TABLE FIU_COPILOT.AML.REGULATORY_CORPUS        TO ROLE FIU_APP_ROLE;
GRANT SELECT ON TABLE FIU_COPILOT.AML.ALERTS                   TO ROLE FIU_APP_ROLE;
GRANT SELECT ON TABLE FIU_COPILOT.AML.TRANSACTIONS             TO ROLE FIU_APP_ROLE;
GRANT SELECT ON VIEW  FIU_COPILOT.AML.ALERT_TXN_SUMMARY        TO ROLE FIU_APP_ROLE;
GRANT SELECT ON VIEW  FIU_COPILOT.AML.ALERTS_CURRENT           TO ROLE FIU_APP_ROLE;
GRANT SELECT ON VIEW  FIU_COPILOT.AML.DECISION_LEDGER_INTEGRITY_V TO ROLE FIU_APP_ROLE;

-- The append-only ledger.
GRANT SELECT, INSERT ON TABLE FIU_COPILOT.AML.DECISION_LEDGER TO ROLE FIU_APP_ROLE;
REVOKE UPDATE, DELETE, TRUNCATE, REFERENCES ON TABLE FIU_COPILOT.AML.DECISION_LEDGER FROM ROLE FIU_APP_ROLE;

-- Cortex: Complete (database role), Search service, Analyst semantic model.
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE FIU_APP_ROLE;
GRANT USAGE ON CORTEX SEARCH SERVICE FIU_COPILOT.AML.CORPUS_SEARCH TO ROLE FIU_APP_ROLE;
GRANT READ  ON STAGE FIU_COPILOT.AML.SEMANTIC_STAGE TO ROLE FIU_APP_ROLE;
