-- 10_governance_remove.sql — undo 10_governance_optin.sql. Run as FIU_ADMIN_ROLE. Idempotent. Touches no data and no other object.
--     python3 scripts/governance_policies.py remove --apply
USE ROLE FIU_ADMIN_ROLE;
USE WAREHOUSE FIU_WH;
USE SCHEMA FIU_COPILOT.AML;

ALTER TABLE TRANSACTIONS MODIFY COLUMN COUNTERPARTY UNSET MASKING POLICY;
ALTER TABLE ALERTS MODIFY COLUMN CUSTOMER_PROFILE UNSET MASKING POLICY;
DROP MASKING POLICY IF EXISTS MASK_COUNTERPARTY;
DROP MASKING POLICY IF EXISTS MASK_CUSTOMER_PROFILE;
